#!/usr/bin/env php
<?php

/**
 * This file is part of the Confman project.
 *
 * (c) Alex "Pierstoval" Rock <pierstoval@gmail.com>
 *
 * This source file is subject to the AGPL-3.0 license that is bundled
 * with this source code in the file LICENSE
 */

use Pierstoval\Confman\App;
use Pierstoval\Confman\Command\Config;
use Pierstoval\Confman\Command\Git;
use Pierstoval\Confman\Command\Project;
use Pierstoval\Confman\Command\RunCommands;

require __DIR__.'/vendor/autoload.php';

$PHPBIN = PHP_BINARY;

const APP_VERSION = 'v0.1.12';

$app = new App();

$app->addCommand(new Project\ProjectsList($app));
$app->addCommand(new Project\ProjectAdd($app));
$app->addCommand(new Config\ConfigCreate($app));
$app->addCommand(new Config\ConfigList($app));
$app->addCommand(new RunCommands($app));
$app->addCommand(new Git\GitFetch($app));

$app->run();
