#!/usr/bin/env php
<?php

if (!isset($argv[1]) || !is_file($argv[1])) {
    echo "Could not find commit message…";
    exit(1);
}

$commitMsg = file_get_contents($argv[1]);
if (!preg_match('~(tag|release) +v?(?<tag>\d+\.\d+\.\d+)~iUu', $commitMsg, $matches)) {
    // Not a tag.
    return;
}

$tag = 'v'.$matches['tag'];

$cwd = getcwd();
if (false === $cwd) {
    echo "Could not determine current directory.";
    exit(1);
}
$mainFile = $cwd.'/run';
if (!is_file($mainFile)) {
    echo "Could not get main file content.";
    exit(1);
}

$cnt = file_get_contents($mainFile);
if (!str_contains($cnt, "const APP_VERSION = 'v")) {
    echo "Could not find version in main file.";
    exit(1);
}
$cnt = preg_replace("~const APP_VERSION = 'v[^']+';~", "const APP_VERSION = '$tag';", $cnt);

if (false === file_put_contents($mainFile, $cnt)) {
    echo "Could not update version in main file.";
    exit(1);
}

if (false === file_put_contents('tagname', $tag)) {
    echo "Could not save tag name.";
    exit(1);
}

file_put_contents('tagname', $tag);

echo "Updated version in main file ✅\n";
